import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'; // Include Bootstrap CSS
import 'font-awesome/css/font-awesome.min.css'; // Include Font Awesome CSS
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
